ALTER TABLE KhoaHoc ADD ThoiGianHocDuKien INT NULL;
ALTER TABLE KhoaHoc ADD ThoiGianChoPhepTre INT NULL;
ALTER TABLE TienDo ADD NgayKetThuc DATETIME NULL;

CREATE TABLE ThongBao (
    MaThongBao INT IDENTITY(1,1) PRIMARY KEY,
    MaNguoiDung INT NOT NULL,
    TieuDe NVARCHAR(255) NOT NULL,
    NoiDung NVARCHAR(MAX) NOT NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    DaDoc BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_ThongBao_NguoiDung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung) ON DELETE CASCADE
);
